package main

import (
	docs "smart-contract-verify/docs" // docs is generated by Swag CLI, you have to import it.
	"smart-contract-verify/repository"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Verify Smart Contract API
// @version 1.0
// @description This is a smart contract verify application
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email soberkoder@gmail.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host verify.serenity.aura.network
// @BasePath /
func main() {
	smartContractRepo := repository.New()
	router := gin.Default()

	router.Use(cors.New(cors.Config{
		AllowOrigins: []string{"*"},
		AllowMethods: []string{"POST", "PUT", "PATCH", "DELETE"},
		AllowHeaders: []string{"Content-Type,Access-Control-Allow-Origin, Access-Control-Allow-Headers"},
	}))

	docs.SwaggerInfo.BasePath = "/api/v1"
	v1 := router.Group("/api/v1")
	{
		eg := v1.Group("/smart-contract")
		{
			eg.POST("/verify", smartContractRepo.CallVerifyContractCode)
			eg.GET("/get-hash/:contractId", smartContractRepo.CallGetContractHash)
			eg.GET("get-unverified-contract/:contractHash", smartContractRepo.TestQueryGetAll)
		}
	}

	url := ginSwagger.URL("https://verify.serenity.aura.network/swagger/doc.json") // The url pointing to API definition
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler, url))
	router.Run() // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
}
