package main

import (
	docs "smart-contract-verify/docs" // docs is generated by Swag CLI, you have to import it.
	"smart-contract-verify/repository"

	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Verify Smart Contract API
// @version 1.0
// @description This is a smart contract verify application
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email soberkoder@gmail.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /
func main() {
	// contractUrl := "https://drive.google.com/u/0/uc?id=1lZ-npBwTt4AEMLImrzw0k4X997yiTosW&export=download"
	// dockerImage := "cosmwasm/rust-optimizer:0.10.7"
	// contractAddress := "aura1r9jswv0rfywh809d8rpfcw0lqlfs6tw079tn5v0p4z0mt4zea6ksguvh69"
	// rpc := "http://34.199.79.132:26657"

	// verify := VerifyContractCode(contractUrl, dockerImage, contractAddress, rpc)
	// log.Println("Smart contract verified: " + strconv.FormatBool(verify))

	smartContractRepo := repository.New()
	router := gin.Default()
	docs.SwaggerInfo.BasePath = "/api/v1"
	v1 := router.Group("/api/v1")
	{
		eg := v1.Group("/smart-contract")
		{
			eg.POST("/verify", smartContractRepo.CallVerifyContractCode)
			eg.GET("/get-hash/:contractId", smartContractRepo.CallGetContractHash)
		}
	}

	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler, url))
	router.Run("localhost:8080") // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
}
